create database HydroConsumer;
USE HYDROCONSUMER;

CREATE TABLE CONSUMER(
CONSUMERID BIGINT PRIMARY KEY NOT NULL,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
CITY VARCHAR(50),
BILLAMOUNT FLOAT,
DUEDATE DATE
);

ALTER TABLE CONSUMER
ADD PAID INT DEFAULT 0 CHECK(PAID = 0 OR PAID = 1);

ALTER TABLE CONSUMER
DROP COLUMN PAID;

use hydroconsumer;
select * from consumer;

CREATE TABLE LOGIN(
USERNAME VARCHAR(10) PRIMARY KEY NOT NULL,
PASSWORD VARCHAR(10)
);

DROP TABLE LOGIN;

insert into login values('admin','password');
insert into login values('n01150847','n01150847');

SELECT * FROM LOGIN;
